# Generated by Django 4.2 on 2023-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdressUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry', models.CharField(choices=[('FRANCE', 'FRANCE'), ('ALLEMAGNE', 'ALLEMAGNE'), ('CAMEROUN', 'CAMEROUN'), ('GABON', 'GABON')], default='CAMEROUN', max_length=10)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('adress', models.TextField()),
                ('code_postal', models.CharField(blank=True, max_length=34, null=True)),
            ],
        ),
    ]
