# Generated by Django 4.2 on 2023-05-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0002_alter_adressuser_adress_alter_adressuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressuser',
            name='adress',
            field=models.TextField(),
        ),
    ]
