# Generated by Django 4.2 on 2023-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0003_alter_adressuser_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressuser',
            name='adress',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
