# Generated by Django 4.2 on 2023-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0004_alter_adressuser_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adressuser',
            name='code_postal',
            field=models.IntegerField(unique=True),
        ),
    ]
