# Generated by Django 4.2 on 2023-04-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordere_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
